development:
  adapter: postgresql
  database: zolodb
  pool: 5
  timeout: 5000
  username: zelohr
  password: 


test:
  adapter: postgresql

  database: zolodb

  pool: 5
  timeout: 5000
  username: zelohr
  password: 

production:
  adapter: postgresql
  encoding: unicode
  database: zolodb

  pool: 5
  timeout: 5000
  username: zelohr
  password: 

