# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7263b0d6271d7b87e6692a9a1d8dd8302087dbb8af6cc7534b3b51e56d4eb3ecc71a525d7e6e07372fefeff4b254250319d710a2ad2b769e27d65104fbb402f1

test:
  secret_key_base: 4a972667520e161a9754a7f7ddc561ac9e900ed3192c04485a70288215d8b875fd6836be371d29308596ec7cc28337e6e12a1c87509e10a84cba6b7d1e768b95

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
